spring:
  application:
    name: CONFIG-DEV

# This application will use the url provided to register with the server.
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
